version: '3.9'

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  postgres:
    image: fsvbj83hfwpk/emergencyfood-postgres
    build:
      context: ./postgres/
    volumes:
      - ~/emergencyfood.dev/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
  backend:
    image: fsvbj83hfwpk/emergencyfood-backend
    build:
      context: ../../
      dockerfile: ./infrastructure/docker/backend/Dockerfile
    command: waitress-serve --listen 0.0.0.0:8000 emergencyfood.wsgi:application
    volumes:
      - ~/emergencyfood.dev/static:/var/www/emergencyfood.dev/static/
      - ~/emergencyfood.dev/media/:/var/www/emergencyfood.dev/media/
    expose:
      - 8000
    depends_on:
      - postgres
  nginx:
    image: fsvbj83hfwpk/emergencyfood-nginx
    build: ./nginx/
    ports: 
      - 1337:80
    volumes:
      - ~/emergencyfood.dev/static:/var/www/emergencyfood.dev/static/
      - ~/emergencyfood.dev/media/:/var/www/emergencyfood.dev/media/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backend