name: Build and Release to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build images
        run: docker-compose -f .docker/production/docker-compose.yml build

      - name: Release images
        run: |
          docker login
          docker-compose -f .docker/production/docker-compose.yml push
